deps: revert update kubernetes packages to v0.35.0 (#94)
This reverts commit ccb46d6ad8cf9f41d289f1fa3bfd1b69a62a34dd.

There seem to be a mismatch between the k8s api version in cert-manager and the one in the webhook. The webhook then fails with the following error:

          Error: error installing APIGroup for solvers: unable to get openapi models: cannot find model definition for io.k8s.apimachinery.pkg.apis.meta.v1.TypeMeta. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again